# Generated by Django 5.2.8 on 2026-05-21 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-cart", "Shopping Cart"),
                            ("bi-airplane", "Travel"),
                            ("bi-house", "Home"),
                            ("bi-lightning", "Bills"),
                            ("bi-cup-straw", "Food & Drink"),
                            ("bi-heart-pulse", "Health"),
                            ("bi-controller", "Entertainment"),
                            ("bi-book", "Education"),
                            ("bi-three-dots", "Other"),
                        ],
                        default="bi-three-dots",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF6384", "Red"),
                            ("#36A2EB", "Blue"),
                            ("#FFCE56", "Yellow"),
                            ("#4BC0C0", "Teal"),
                            ("#9966FF", "Purple"),
                            ("#FF9F40", "Orange"),
                            ("#FF6384", "Pink"),
                            ("#C9CBCF", "Grey"),
                        ],
                        default="#36A2EB",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
